#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wal-mart.com/", ConfigurationName="Importing.WebGuardian.ServiceWebGuardianSoap")]
    internal interface ServiceWebGuardianSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ValidarAcesso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.Status ValidarAcesso(string login, string senha, int codigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ValidarAcesso", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.Status> ValidarAcessoAsync(string login, string senha, int codigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/AlterarSenha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.Status AlterarSenha(string login, string senha, string novaSenha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/AlterarSenha", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.Status> AlterarSenhaAsync(string login, string senha, string novaSenha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.UsuarioResultado ObterUsuario(string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.UsuarioResultado> ObterUsuarioAsync(string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterAplicacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.AplicacaoResultado ObterAplicacao(int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterAplicacao", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.AplicacaoResultado> ObterAplicacaoAsync(int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterAplicacoes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.AplicacoesResultado ObterAplicacoes(bool apenasAtivas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterAplicacoes", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.AplicacoesResultado> ObterAplicacoesAsync(bool apenasAtivas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterUsuariosAplicacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.UsuariosAplicacaoResultado ObterUsuariosAplicacao(string login, string senha, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterUsuariosAplicacao", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.UsuariosAplicacaoResultado> ObterUsuariosAplicacaoAsync(string login, string senha, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterPerfisUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfisResultado ObterPerfisUsuario(string login, string senha, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterPerfisUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfisResultado> ObterPerfisUsuarioAsync(string login, string senha, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterPerfisOutroUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfisResultado ObterPerfisOutroUsuario(string login, string senha, string loginProcurado, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterPerfisOutroUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfisResultado> ObterPerfisOutroUsuarioAsync(string login, string senha, string loginProcurado, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterPerfisAplicacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfisResultado ObterPerfisAplicacao(int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterPerfisAplicacao", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfisResultado> ObterPerfisAplicacaoAsync(int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterPerfil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfilResultado ObterPerfil(int codigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterPerfil", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfilResultado> ObterPerfilAsync(int codigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterFormulario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.FormularioResultado ObterFormulario(string login, string senha, int codigoFormulario, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterFormulario", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.FormularioResultado> ObterFormularioAsync(string login, string senha, int codigoFormulario, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterFormulariosAplicacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.FormulariosAplicacaoResultado ObterFormulariosAplicacao(string login, string senha, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterFormulariosAplicacao", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.FormulariosAplicacaoResultado> ObterFormulariosAplicacaoAsync(string login, string senha, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterMenusAplicacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.MenusAplicacaoResultado ObterMenusAplicacao(string login, string senha, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterMenusAplicacao", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.MenusAplicacaoResultado> ObterMenusAplicacaoAsync(string login, string senha, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterEventosAplicacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.EventosAplicacaoResultado ObterEventosAplicacao(string login, string senha, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterEventosAplicacao", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.EventosAplicacaoResultado> ObterEventosAplicacaoAsync(string login, string senha, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterPermissoesPerfil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PermissoesResultado ObterPermissoesPerfil(string login, string senha, int codigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterPermissoesPerfil", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PermissoesResultado> ObterPermissoesPerfilAsync(string login, string senha, int codigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterPermissoesPerfilFormulario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PermissoesResultado ObterPermissoesPerfilFormulario(string login, string senha, int codigoPerfil, int codigoFormulario, int codigoAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wal-mart.com/ObterPermissoesPerfilFormulario", ReplyAction="*")]
        System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PermissoesResultado> ObterPermissoesPerfilFormularioAsync(string login, string senha, int codigoPerfil, int codigoFormulario, int codigoAplicacao);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoRetornoField;
        
        private string retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CodigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
                this.RaisePropertyChanged("CodigoRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("Retorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class PermissoesTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PerfilTO perfilField;
        
        private EventoTO[] eventosField;
        
        private MenuTO[] menusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PerfilTO Perfil {
            get {
                return this.perfilField;
            }
            set {
                this.perfilField = value;
                this.RaisePropertyChanged("Perfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public EventoTO[] Eventos {
            get {
                return this.eventosField;
            }
            set {
                this.eventosField = value;
                this.RaisePropertyChanged("Eventos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public MenuTO[] Menus {
            get {
                return this.menusField;
            }
            set {
                this.menusField = value;
                this.RaisePropertyChanged("Menus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class PerfilTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string nomeField;
        
        private string descricaoField;
        
        private int timeOutField;
        
        private System.DateTime dt_InclusaoField;
        
        private enStatus statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TimeOut {
            get {
                return this.timeOutField;
            }
            set {
                this.timeOutField = value;
                this.RaisePropertyChanged("TimeOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Dt_Inclusao {
            get {
                return this.dt_InclusaoField;
            }
            set {
                this.dt_InclusaoField = value;
                this.RaisePropertyChanged("Dt_Inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public enStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public enum enStatus {
        
        /// <remarks/>
        stAtivo,
        
        /// <remarks/>
        stInativo,
        
        /// <remarks/>
        stCancelado,
        
        /// <remarks/>
        stSenhaExpirada,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class EventoTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string nomeField;
        
        private string descricaoField;
        
        private string iconeField;
        
        private string urlField;
        
        private string imageField;
        
        private string targetField;
        
        private System.DateTime dt_InclusaoField;
        
        private enStatus statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Icone {
            get {
                return this.iconeField;
            }
            set {
                this.iconeField = value;
                this.RaisePropertyChanged("Icone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("Target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime Dt_Inclusao {
            get {
                return this.dt_InclusaoField;
            }
            set {
                this.dt_InclusaoField = value;
                this.RaisePropertyChanged("Dt_Inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public enStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class MenuTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string nomeField;
        
        private string descricaoField;
        
        private string iconeField;
        
        private string urlField;
        
        private string imageField;
        
        private string targetField;
        
        private System.Nullable<int> codigoMenuPaiField;
        
        private System.Nullable<int> codigoMenuFilhoField;
        
        private System.Nullable<int> posicaoField;
        
        private string iconeHotField;
        
        private string iconeDesativadoField;
        
        private System.Nullable<int> codigo_Formulario_FilhoField;
        
        private System.DateTime dt_InclusaoField;
        
        private enStatus statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Icone {
            get {
                return this.iconeField;
            }
            set {
                this.iconeField = value;
                this.RaisePropertyChanged("Icone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("Target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> CodigoMenuPai {
            get {
                return this.codigoMenuPaiField;
            }
            set {
                this.codigoMenuPaiField = value;
                this.RaisePropertyChanged("CodigoMenuPai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> CodigoMenuFilho {
            get {
                return this.codigoMenuFilhoField;
            }
            set {
                this.codigoMenuFilhoField = value;
                this.RaisePropertyChanged("CodigoMenuFilho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> Posicao {
            get {
                return this.posicaoField;
            }
            set {
                this.posicaoField = value;
                this.RaisePropertyChanged("Posicao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string IconeHot {
            get {
                return this.iconeHotField;
            }
            set {
                this.iconeHotField = value;
                this.RaisePropertyChanged("IconeHot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string IconeDesativado {
            get {
                return this.iconeDesativadoField;
            }
            set {
                this.iconeDesativadoField = value;
                this.RaisePropertyChanged("IconeDesativado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> Codigo_Formulario_Filho {
            get {
                return this.codigo_Formulario_FilhoField;
            }
            set {
                this.codigo_Formulario_FilhoField = value;
                this.RaisePropertyChanged("Codigo_Formulario_Filho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime Dt_Inclusao {
            get {
                return this.dt_InclusaoField;
            }
            set {
                this.dt_InclusaoField = value;
                this.RaisePropertyChanged("Dt_Inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public enStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class PermissoesResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PermissoesTO permissoesField;
        
        private Status statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PermissoesTO Permissoes {
            get {
                return this.permissoesField;
            }
            set {
                this.permissoesField = value;
                this.RaisePropertyChanged("Permissoes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class EventosAplicacaoResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EventoTO[] eventosField;
        
        private Status statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public EventoTO[] Eventos {
            get {
                return this.eventosField;
            }
            set {
                this.eventosField = value;
                this.RaisePropertyChanged("Eventos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class MenusAplicacaoResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MenuTO[] menusField;
        
        private Status statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public MenuTO[] Menus {
            get {
                return this.menusField;
            }
            set {
                this.menusField = value;
                this.RaisePropertyChanged("Menus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class FormulariosAplicacaoResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FormularioTO[] formulariosField;
        
        private Status statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public FormularioTO[] Formularios {
            get {
                return this.formulariosField;
            }
            set {
                this.formulariosField = value;
                this.RaisePropertyChanged("Formularios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class FormularioTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string nomeField;
        
        private string descricaoField;
        
        private enStatus statusField;
        
        private System.DateTime dt_InclusaoField;
        
        private EventoTO[] eventosField;
        
        private MenuTO[] menusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public enStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Dt_Inclusao {
            get {
                return this.dt_InclusaoField;
            }
            set {
                this.dt_InclusaoField = value;
                this.RaisePropertyChanged("Dt_Inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public EventoTO[] Eventos {
            get {
                return this.eventosField;
            }
            set {
                this.eventosField = value;
                this.RaisePropertyChanged("Eventos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public MenuTO[] Menus {
            get {
                return this.menusField;
            }
            set {
                this.menusField = value;
                this.RaisePropertyChanged("Menus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class FormularioResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FormularioTO formularioField;
        
        private Status statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FormularioTO Formulario {
            get {
                return this.formularioField;
            }
            set {
                this.formularioField = value;
                this.RaisePropertyChanged("Formulario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class PerfilResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PerfilTO perfilField;
        
        private Status statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PerfilTO Perfil {
            get {
                return this.perfilField;
            }
            set {
                this.perfilField = value;
                this.RaisePropertyChanged("Perfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class PerfisResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PerfilTO[] perfisField;
        
        private Status statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public PerfilTO[] Perfis {
            get {
                return this.perfisField;
            }
            set {
                this.perfisField = value;
                this.RaisePropertyChanged("Perfis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class UsuariosAplicacaoResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UsuarioTO[] usuariosField;
        
        private Status statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public UsuarioTO[] Usuarios {
            get {
                return this.usuariosField;
            }
            set {
                this.usuariosField = value;
                this.RaisePropertyChanged("Usuarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class UsuarioTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string loginField;
        
        private string senhaField;
        
        private string nomeField;
        
        private string departamentoField;
        
        private string cargoField;
        
        private string telefone_ResField;
        
        private string telefone_ComField;
        
        private string telefone_CelField;
        
        private string emailField;
        
        private string ramalField;
        
        private string webPageField;
        
        private string paisField;
        
        private string enderecoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string estadoField;
        
        private string cEPField;
        
        private bool locadoField;
        
        private string categoriaField;
        
        private System.Nullable<System.DateTime> dt_InclusaoField;
        
        private System.Nullable<System.DateTime> dt_Expiracao_SenhaField;
        
        private enStatus statusField;
        
        private int qtd_Tentativas_LoginField;
        
        private string chapaField;
        
        private System.Nullable<System.DateTime> dt_EfetivaInicioField;
        
        private System.Nullable<System.DateTime> dt_EfetivaTerminoField;
        
        private string fornecedorField;
        
        private string unidade_NegocioField;
        
        private System.Nullable<int> codigo_LojaField;
        
        private string cPFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("Senha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("Departamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("Cargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Telefone_Res {
            get {
                return this.telefone_ResField;
            }
            set {
                this.telefone_ResField = value;
                this.RaisePropertyChanged("Telefone_Res");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Telefone_Com {
            get {
                return this.telefone_ComField;
            }
            set {
                this.telefone_ComField = value;
                this.RaisePropertyChanged("Telefone_Com");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Telefone_Cel {
            get {
                return this.telefone_CelField;
            }
            set {
                this.telefone_CelField = value;
                this.RaisePropertyChanged("Telefone_Cel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Ramal {
            get {
                return this.ramalField;
            }
            set {
                this.ramalField = value;
                this.RaisePropertyChanged("Ramal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string WebPage {
            get {
                return this.webPageField;
            }
            set {
                this.webPageField = value;
                this.RaisePropertyChanged("WebPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("Pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
                this.RaisePropertyChanged("Endereco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("Bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
                this.RaisePropertyChanged("Cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
                this.RaisePropertyChanged("CEP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool Locado {
            get {
                return this.locadoField;
            }
            set {
                this.locadoField = value;
                this.RaisePropertyChanged("Locado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("Categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<System.DateTime> Dt_Inclusao {
            get {
                return this.dt_InclusaoField;
            }
            set {
                this.dt_InclusaoField = value;
                this.RaisePropertyChanged("Dt_Inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<System.DateTime> Dt_Expiracao_Senha {
            get {
                return this.dt_Expiracao_SenhaField;
            }
            set {
                this.dt_Expiracao_SenhaField = value;
                this.RaisePropertyChanged("Dt_Expiracao_Senha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public enStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int Qtd_Tentativas_Login {
            get {
                return this.qtd_Tentativas_LoginField;
            }
            set {
                this.qtd_Tentativas_LoginField = value;
                this.RaisePropertyChanged("Qtd_Tentativas_Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Chapa {
            get {
                return this.chapaField;
            }
            set {
                this.chapaField = value;
                this.RaisePropertyChanged("Chapa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<System.DateTime> Dt_EfetivaInicio {
            get {
                return this.dt_EfetivaInicioField;
            }
            set {
                this.dt_EfetivaInicioField = value;
                this.RaisePropertyChanged("Dt_EfetivaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public System.Nullable<System.DateTime> Dt_EfetivaTermino {
            get {
                return this.dt_EfetivaTerminoField;
            }
            set {
                this.dt_EfetivaTerminoField = value;
                this.RaisePropertyChanged("Dt_EfetivaTermino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Fornecedor {
            get {
                return this.fornecedorField;
            }
            set {
                this.fornecedorField = value;
                this.RaisePropertyChanged("Fornecedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Unidade_Negocio {
            get {
                return this.unidade_NegocioField;
            }
            set {
                this.unidade_NegocioField = value;
                this.RaisePropertyChanged("Unidade_Negocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<int> Codigo_Loja {
            get {
                return this.codigo_LojaField;
            }
            set {
                this.codigo_LojaField = value;
                this.RaisePropertyChanged("Codigo_Loja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
                this.RaisePropertyChanged("CPF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class AplicacoesResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AplicacaoTO[] aplicacoesField;
        
        private Status statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public AplicacaoTO[] Aplicacoes {
            get {
                return this.aplicacoesField;
            }
            set {
                this.aplicacoesField = value;
                this.RaisePropertyChanged("Aplicacoes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class AplicacaoTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string cd_SiglaField;
        
        private string nomeField;
        
        private string descricaoField;
        
        private string versaoField;
        
        private string iconeField;
        
        private string url_cssField;
        
        private string prioridadeField;
        
        private System.Nullable<int> usuario_CoordenadorField;
        
        private System.Nullable<System.DateTime> dt_InclusaoField;
        
        private enStatus statusField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Cd_Sigla {
            get {
                return this.cd_SiglaField;
            }
            set {
                this.cd_SiglaField = value;
                this.RaisePropertyChanged("Cd_Sigla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("Descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
                this.RaisePropertyChanged("Versao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Icone {
            get {
                return this.iconeField;
            }
            set {
                this.iconeField = value;
                this.RaisePropertyChanged("Icone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Url_css {
            get {
                return this.url_cssField;
            }
            set {
                this.url_cssField = value;
                this.RaisePropertyChanged("Url_css");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Prioridade {
            get {
                return this.prioridadeField;
            }
            set {
                this.prioridadeField = value;
                this.RaisePropertyChanged("Prioridade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> Usuario_Coordenador {
            get {
                return this.usuario_CoordenadorField;
            }
            set {
                this.usuario_CoordenadorField = value;
                this.RaisePropertyChanged("Usuario_Coordenador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> Dt_Inclusao {
            get {
                return this.dt_InclusaoField;
            }
            set {
                this.dt_InclusaoField = value;
                this.RaisePropertyChanged("Dt_Inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public enStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class AplicacaoResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AplicacaoTO aplicacaoField;
        
        private Status statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AplicacaoTO Aplicacao {
            get {
                return this.aplicacaoField;
            }
            set {
                this.aplicacaoField = value;
                this.RaisePropertyChanged("Aplicacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wal-mart.com/")]
    public partial class UsuarioResultado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UsuarioTO usuarioField;
        
        private Status statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UsuarioTO Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ServiceWebGuardianSoapChannel : Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.ServiceWebGuardianSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ServiceWebGuardianSoapClient : System.ServiceModel.ClientBase<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.ServiceWebGuardianSoap>, Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.ServiceWebGuardianSoap {
        
        public ServiceWebGuardianSoapClient() {
        }
        
        public ServiceWebGuardianSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWebGuardianSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWebGuardianSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWebGuardianSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.Status ValidarAcesso(string login, string senha, int codigoPerfil) {
            return base.Channel.ValidarAcesso(login, senha, codigoPerfil);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.Status> ValidarAcessoAsync(string login, string senha, int codigoPerfil) {
            return base.Channel.ValidarAcessoAsync(login, senha, codigoPerfil);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.Status AlterarSenha(string login, string senha, string novaSenha) {
            return base.Channel.AlterarSenha(login, senha, novaSenha);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.Status> AlterarSenhaAsync(string login, string senha, string novaSenha) {
            return base.Channel.AlterarSenhaAsync(login, senha, novaSenha);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.UsuarioResultado ObterUsuario(string login, string senha) {
            return base.Channel.ObterUsuario(login, senha);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.UsuarioResultado> ObterUsuarioAsync(string login, string senha) {
            return base.Channel.ObterUsuarioAsync(login, senha);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.AplicacaoResultado ObterAplicacao(int codigoAplicacao) {
            return base.Channel.ObterAplicacao(codigoAplicacao);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.AplicacaoResultado> ObterAplicacaoAsync(int codigoAplicacao) {
            return base.Channel.ObterAplicacaoAsync(codigoAplicacao);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.AplicacoesResultado ObterAplicacoes(bool apenasAtivas) {
            return base.Channel.ObterAplicacoes(apenasAtivas);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.AplicacoesResultado> ObterAplicacoesAsync(bool apenasAtivas) {
            return base.Channel.ObterAplicacoesAsync(apenasAtivas);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.UsuariosAplicacaoResultado ObterUsuariosAplicacao(string login, string senha, int codigoAplicacao) {
            return base.Channel.ObterUsuariosAplicacao(login, senha, codigoAplicacao);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.UsuariosAplicacaoResultado> ObterUsuariosAplicacaoAsync(string login, string senha, int codigoAplicacao) {
            return base.Channel.ObterUsuariosAplicacaoAsync(login, senha, codigoAplicacao);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfisResultado ObterPerfisUsuario(string login, string senha, int codigoAplicacao) {
            return base.Channel.ObterPerfisUsuario(login, senha, codigoAplicacao);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfisResultado> ObterPerfisUsuarioAsync(string login, string senha, int codigoAplicacao) {
            return base.Channel.ObterPerfisUsuarioAsync(login, senha, codigoAplicacao);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfisResultado ObterPerfisOutroUsuario(string login, string senha, string loginProcurado, int codigoAplicacao) {
            return base.Channel.ObterPerfisOutroUsuario(login, senha, loginProcurado, codigoAplicacao);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfisResultado> ObterPerfisOutroUsuarioAsync(string login, string senha, string loginProcurado, int codigoAplicacao) {
            return base.Channel.ObterPerfisOutroUsuarioAsync(login, senha, loginProcurado, codigoAplicacao);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfisResultado ObterPerfisAplicacao(int codigoAplicacao) {
            return base.Channel.ObterPerfisAplicacao(codigoAplicacao);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfisResultado> ObterPerfisAplicacaoAsync(int codigoAplicacao) {
            return base.Channel.ObterPerfisAplicacaoAsync(codigoAplicacao);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfilResultado ObterPerfil(int codigoPerfil) {
            return base.Channel.ObterPerfil(codigoPerfil);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PerfilResultado> ObterPerfilAsync(int codigoPerfil) {
            return base.Channel.ObterPerfilAsync(codigoPerfil);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.FormularioResultado ObterFormulario(string login, string senha, int codigoFormulario, int codigoAplicacao) {
            return base.Channel.ObterFormulario(login, senha, codigoFormulario, codigoAplicacao);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.FormularioResultado> ObterFormularioAsync(string login, string senha, int codigoFormulario, int codigoAplicacao) {
            return base.Channel.ObterFormularioAsync(login, senha, codigoFormulario, codigoAplicacao);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.FormulariosAplicacaoResultado ObterFormulariosAplicacao(string login, string senha, int codigoAplicacao) {
            return base.Channel.ObterFormulariosAplicacao(login, senha, codigoAplicacao);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.FormulariosAplicacaoResultado> ObterFormulariosAplicacaoAsync(string login, string senha, int codigoAplicacao) {
            return base.Channel.ObterFormulariosAplicacaoAsync(login, senha, codigoAplicacao);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.MenusAplicacaoResultado ObterMenusAplicacao(string login, string senha, int codigoAplicacao) {
            return base.Channel.ObterMenusAplicacao(login, senha, codigoAplicacao);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.MenusAplicacaoResultado> ObterMenusAplicacaoAsync(string login, string senha, int codigoAplicacao) {
            return base.Channel.ObterMenusAplicacaoAsync(login, senha, codigoAplicacao);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.EventosAplicacaoResultado ObterEventosAplicacao(string login, string senha, int codigoAplicacao) {
            return base.Channel.ObterEventosAplicacao(login, senha, codigoAplicacao);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.EventosAplicacaoResultado> ObterEventosAplicacaoAsync(string login, string senha, int codigoAplicacao) {
            return base.Channel.ObterEventosAplicacaoAsync(login, senha, codigoAplicacao);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PermissoesResultado ObterPermissoesPerfil(string login, string senha, int codigoPerfil) {
            return base.Channel.ObterPermissoesPerfil(login, senha, codigoPerfil);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PermissoesResultado> ObterPermissoesPerfilAsync(string login, string senha, int codigoPerfil) {
            return base.Channel.ObterPermissoesPerfilAsync(login, senha, codigoPerfil);
        }
        
        public Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PermissoesResultado ObterPermissoesPerfilFormulario(string login, string senha, int codigoPerfil, int codigoFormulario, int codigoAplicacao) {
            return base.Channel.ObterPermissoesPerfilFormulario(login, senha, codigoPerfil, codigoFormulario, codigoAplicacao);
        }
        
        public System.Threading.Tasks.Task<Walmart.Sgp.Infrastructure.IO.Importing.WebGuardian.PermissoesResultado> ObterPermissoesPerfilFormularioAsync(string login, string senha, int codigoPerfil, int codigoFormulario, int codigoAplicacao) {
            return base.Channel.ObterPermissoesPerfilFormularioAsync(login, senha, codigoPerfil, codigoFormulario, codigoAplicacao);
        }
    }
}
#pragma warning restore 1591