SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RelacaoItemCD](
	[idRelacaoItemCD] [bigint] IDENTITY(1,1) NOT NULL,
	[idItemEntrada] [bigint] NOT NULL,
	[idItemSaida] [bigint] NULL,
	[idCD] [int] NOT NULL,
	[vlTipoReabastecimento] [smallint] NOT NULL,
	[vlEstoqueSeguranca] [int] NULL,
 CONSTRAINT [PK_RelacaoItemCD] PRIMARY KEY CLUSTERED 
(
	[IDRelacaoItemCD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[RelacaoItemCD]  WITH CHECK ADD  CONSTRAINT [FK_RelacaoItemCD_idItemEntrada] FOREIGN KEY([idItemEntrada])
REFERENCES [dbo].[ItemDetalhe] ([IDItemDetalhe])
GO

ALTER TABLE [dbo].[RelacaoItemCD] CHECK CONSTRAINT [FK_RelacaoItemCD_idItemEntrada]
GO

ALTER TABLE [dbo].[RelacaoItemCD]  WITH CHECK ADD  CONSTRAINT [FK_RelacaoItemCD_idItemSaida] FOREIGN KEY([idItemSaida])
REFERENCES [dbo].[ItemDetalhe] ([IDItemDetalhe])
GO

ALTER TABLE [dbo].[RelacaoItemCD] CHECK CONSTRAINT [FK_RelacaoItemCD_idItemSaida]
GO

CREATE NONCLUSTERED INDEX [IX_RelacaoItemCD_idItemEntrada] ON [dbo].[RelacaoItemCD] 
(
	[idItemEntrada] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_RelacaoItemCD_idItemSaida] ON [dbo].[RelacaoItemCD] 
(
	[idItemSaida] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

