--CRIA A TABELA PARA A VIEW VW_REAB_ITENSENVIOOMSXD 
CREATE TABLE AutorizaVendorECd
(
	[idAutorizaVendorECd] [int] NOT NULL IDENTITY(1,1),
	[idCD] [int] NOT NULL,
	[IDFornecedorParametro] [int] NOT NULL,
	[IDDepartamento] [int] NOT NULL,
	[blAtivo] [bit] NOT NULL
	
 CONSTRAINT [PK_AutorizaVendorECd] PRIMARY KEY CLUSTERED 
(
	[idAutorizaVendorECd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
