// <auto-generated/>
// Gerador para auxiliar na localização de arquivos SQL.
// Os códigos deste arquivo serão compilados.








using System.Diagnostics.CodeAnalysis;

namespace Walmart.Sgp.Infrastructure.Data
{ 
    /// <summary>
    /// Acesso aos arquivos de comandos SQL.
    /// </summary>     
    [SuppressMessage("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    internal static class Sql  
    {
        /// <summary>
        /// Comandos SQL relacionados a classe Alcada.
        /// </summary>
        public static class Alcada 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Alcada.ObterEstruturado.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturado = new CommandInfo( "ObterEstruturado", "Alcada", "Alcada.ObterEstruturado.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Alcada.ObterEstruturadoPorPerfil.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorPerfil = new CommandInfo( "ObterEstruturadoPorPerfil", "Alcada", "Alcada.ObterEstruturadoPorPerfil.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe AlcadaDetalhe.
        /// </summary>
        public static class AlcadaDetalhe 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo AlcadaDetalhe.ObterPorIdAlcada.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorIdAlcada = new CommandInfo( "ObterPorIdAlcada", "AlcadaDetalhe", "AlcadaDetalhe.ObterPorIdAlcada.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Audit.
        /// </summary>
        public static class Audit 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Audit.ObterRelatorio.sql.
            /// </summary>
            public static readonly CommandInfo ObterRelatorio = new CommandInfo( "ObterRelatorio", "Audit", "Audit.ObterRelatorio.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe AutorizaPedido.
        /// </summary>
        public static class AutorizaPedido 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo AutorizaPedido.ObterAutorizacoesPorSugestaoPedido.sql.
            /// </summary>
            public static readonly CommandInfo ObterAutorizacoesPorSugestaoPedido = new CommandInfo( "ObterAutorizacoesPorSugestaoPedido", "AutorizaPedido", "AutorizaPedido.ObterAutorizacoesPorSugestaoPedido.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Bandeira.
        /// </summary>
        public static class Bandeira 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Bandeira.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "Bandeira", "Bandeira.ObterEstruturadoPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Bandeira.ObterPorIdLoja.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorIdLoja = new CommandInfo( "ObterPorIdLoja", "Bandeira", "Bandeira.ObterPorIdLoja.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Bandeira.ObterPorUsuarioESistema.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorUsuarioESistema = new CommandInfo( "ObterPorUsuarioESistema", "Bandeira", "Bandeira.ObterPorUsuarioESistema.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Bandeira.PesquisarPorFiltros_Count.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltros_Count = new CommandInfo( "PesquisarPorFiltros_Count", "Bandeira", "Bandeira.PesquisarPorFiltros_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Bandeira.PesquisarPorFiltros_Paging.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltros_Paging = new CommandInfo( "PesquisarPorFiltros_Paging", "Bandeira", "Bandeira.PesquisarPorFiltros_Paging.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Categoria.
        /// </summary>
        public static class Categoria 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Categoria.ObterPorCategoriaESistema.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorCategoriaESistema = new CommandInfo( "ObterPorCategoriaESistema", "Categoria", "Categoria.ObterPorCategoriaESistema.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Categoria.PesquisarPorCategoriaDepartamentoESistema.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorCategoriaDepartamentoESistema = new CommandInfo( "PesquisarPorCategoriaDepartamentoESistema", "Categoria", "Categoria.PesquisarPorCategoriaDepartamentoESistema.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe CompraCasada.
        /// </summary>
        public static class CompraCasada 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo CompraCasada.ObterCdPaiPorCdFilho.sql.
            /// </summary>
            public static readonly CommandInfo ObterCdPaiPorCdFilho = new CommandInfo( "ObterCdPaiPorCdFilho", "CompraCasada", "CompraCasada.ObterCdPaiPorCdFilho.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo CompraCasada.Pesquisar.sql.
            /// </summary>
            public static readonly CommandInfo Pesquisar = new CommandInfo( "Pesquisar", "CompraCasada", "CompraCasada.Pesquisar.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo CompraCasada.PesquisarItensEntrada.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarItensEntrada = new CommandInfo( "PesquisarItensEntrada", "CompraCasada", "CompraCasada.PesquisarItensEntrada.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo CompraCasada.PesquisarItensEntrada_Count.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarItensEntrada_Count = new CommandInfo( "PesquisarItensEntrada_Count", "CompraCasada", "CompraCasada.PesquisarItensEntrada_Count.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Departamento.
        /// </summary>
        public static class Departamento 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Departamento.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "Departamento", "Departamento.ObterEstruturadoPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Departamento.ObterPorDepartamentoESistema.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorDepartamentoESistema = new CommandInfo( "ObterPorDepartamentoESistema", "Departamento", "Departamento.ObterPorDepartamentoESistema.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Departamento.PesquisarPorDivisaoESistema.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorDivisaoESistema = new CommandInfo( "PesquisarPorDivisaoESistema", "Departamento", "Departamento.PesquisarPorDivisaoESistema.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Distrito.
        /// </summary>
        public static class Distrito 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Distrito.Pesquisar_Count.sql.
            /// </summary>
            public static readonly CommandInfo Pesquisar_Count = new CommandInfo( "Pesquisar_Count", "Distrito", "Distrito.Pesquisar_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Distrito.Pesquisar_Paging.sql.
            /// </summary>
            public static readonly CommandInfo Pesquisar_Paging = new CommandInfo( "Pesquisar_Paging", "Distrito", "Distrito.Pesquisar_Paging.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Divisao.
        /// </summary>
        public static class Divisao 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Divisao.ObterPorDivisaoESistema.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorDivisaoESistema = new CommandInfo( "ObterPorDivisaoESistema", "Divisao", "Divisao.ObterPorDivisaoESistema.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Divisao.PesquisarPorSistema.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorSistema = new CommandInfo( "PesquisarPorSistema", "Divisao", "Divisao.PesquisarPorSistema.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Estoque.
        /// </summary>
        public static class Estoque 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Estoque.ObterOrigensItem.sql.
            /// </summary>
            public static readonly CommandInfo ObterOrigensItem = new CommandInfo( "ObterOrigensItem", "Estoque", "Estoque.ObterOrigensItem.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Estoque.ObterOsCincoUltimosRecebimentosDoItemPorLoja.sql.
            /// </summary>
            public static readonly CommandInfo ObterOsCincoUltimosRecebimentosDoItemPorLoja = new CommandInfo( "ObterOsCincoUltimosRecebimentosDoItemPorLoja", "Estoque", "Estoque.ObterOsCincoUltimosRecebimentosDoItemPorLoja.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Estoque.ObterUltimoCustoContabilItem.sql.
            /// </summary>
            public static readonly CommandInfo ObterUltimoCustoContabilItem = new CommandInfo( "ObterUltimoCustoContabilItem", "Estoque", "Estoque.ObterUltimoCustoContabilItem.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Estoque.ObterUltimoCustoDoItemNaLoja.sql.
            /// </summary>
            public static readonly CommandInfo ObterUltimoCustoDoItemNaLoja = new CommandInfo( "ObterUltimoCustoDoItemNaLoja", "Estoque", "Estoque.ObterUltimoCustoDoItemNaLoja.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Estoque.ObterUltimoCustoDoItemPorLoja_Count.sql.
            /// </summary>
            public static readonly CommandInfo ObterUltimoCustoDoItemPorLoja_Count = new CommandInfo( "ObterUltimoCustoDoItemPorLoja_Count", "Estoque", "Estoque.ObterUltimoCustoDoItemPorLoja_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Estoque.ObterUltimoCustoDoItemPorLoja_Paging.sql.
            /// </summary>
            public static readonly CommandInfo ObterUltimoCustoDoItemPorLoja_Paging = new CommandInfo( "ObterUltimoCustoDoItemPorLoja_Paging", "Estoque", "Estoque.ObterUltimoCustoDoItemPorLoja_Paging.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe FechamentoFiscal.
        /// </summary>
        public static class FechamentoFiscal 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo FechamentoFiscal.ObterUltimoPorLoja.sql.
            /// </summary>
            public static readonly CommandInfo ObterUltimoPorLoja = new CommandInfo( "ObterUltimoPorLoja", "FechamentoFiscal", "FechamentoFiscal.ObterUltimoPorLoja.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe FineLine.
        /// </summary>
        public static class FineLine 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo FineLine.ObterPorFineLineESistema.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorFineLineESistema = new CommandInfo( "ObterPorFineLineESistema", "FineLine", "FineLine.ObterPorFineLineESistema.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo FineLine.PesquisarPorFineLineSubcategoriaCategoriaDepartamentoESistema.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFineLineSubcategoriaCategoriaDepartamentoESistema = new CommandInfo( "PesquisarPorFineLineSubcategoriaCategoriaDepartamentoESistema", "FineLine", "FineLine.PesquisarPorFineLineSubcategoriaCategoriaDepartamentoESistema.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Fornecedor.
        /// </summary>
        public static class Fornecedor 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Fornecedor.ObterAtivoPorCodigoESistemaComProjecao.sql.
            /// </summary>
            public static readonly CommandInfo ObterAtivoPorCodigoESistemaComProjecao = new CommandInfo( "ObterAtivoPorCodigoESistemaComProjecao", "Fornecedor", "Fornecedor.ObterAtivoPorCodigoESistemaComProjecao.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Fornecedor.ObterPorSistemaCodigoNome.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorSistemaCodigoNome = new CommandInfo( "ObterPorSistemaCodigoNome", "Fornecedor", "Fornecedor.ObterPorSistemaCodigoNome.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Fornecedor.VerificaVendorWalmart.sql.
            /// </summary>
            public static readonly CommandInfo VerificaVendorWalmart = new CommandInfo( "VerificaVendorWalmart", "Fornecedor", "Fornecedor.VerificaVendorWalmart.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe FornecedorParametro.
        /// </summary>
        public static class FornecedorParametro 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo FornecedorParametro.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "FornecedorParametro", "FornecedorParametro.ObterEstruturadoPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo FornecedorParametro.PesquisarItensDSD_Count.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarItensDSD_Count = new CommandInfo( "PesquisarItensDSD_Count", "FornecedorParametro", "FornecedorParametro.PesquisarItensDSD_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo FornecedorParametro.PesquisarPorFiltros.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltros = new CommandInfo( "PesquisarPorFiltros", "FornecedorParametro", "FornecedorParametro.PesquisarPorFiltros.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo FornecedorParametro.PesquisarPorSistemaCodigo9DigitosENomeFornecedor_Count.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorSistemaCodigo9DigitosENomeFornecedor_Count = new CommandInfo( "PesquisarPorSistemaCodigo9DigitosENomeFornecedor_Count", "FornecedorParametro", "FornecedorParametro.PesquisarPorSistemaCodigo9DigitosENomeFornecedor_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo FornecedorParametro.PesquisarPorSistemaCodigo9DigitosENomeFornecedor_Paging.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorSistemaCodigo9DigitosENomeFornecedor_Paging = new CommandInfo( "PesquisarPorSistemaCodigo9DigitosENomeFornecedor_Paging", "FornecedorParametro", "FornecedorParametro.PesquisarPorSistemaCodigo9DigitosENomeFornecedor_Paging.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe GradeSugestao.
        /// </summary>
        public static class GradeSugestao 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo GradeSugestao.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "GradeSugestao", "GradeSugestao.ObterEstruturadoPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo GradeSugestao.ObterGradeSugestoesSeFechada.sql.
            /// </summary>
            public static readonly CommandInfo ObterGradeSugestoesSeFechada = new CommandInfo( "ObterGradeSugestoesSeFechada", "GradeSugestao", "GradeSugestao.ObterGradeSugestoesSeFechada.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo GradeSugestao.PesquisarEstruturadoPorFiltro.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarEstruturadoPorFiltro = new CommandInfo( "PesquisarEstruturadoPorFiltro", "GradeSugestao", "GradeSugestao.PesquisarEstruturadoPorFiltro.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Inventario.
        /// </summary>
        public static class Inventario 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Inventario.ContarInventarios.sql.
            /// </summary>
            public static readonly CommandInfo ContarInventarios = new CommandInfo( "ContarInventarios", "Inventario", "Inventario.ContarInventarios.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Inventario.ObterCustoTotalPorFiltro.sql.
            /// </summary>
            public static readonly CommandInfo ObterCustoTotalPorFiltro = new CommandInfo( "ObterCustoTotalPorFiltro", "Inventario", "Inventario.ObterCustoTotalPorFiltro.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Inventario.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "Inventario", "Inventario.ObterEstruturadoPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Inventario.ObterSumarizadoPorFiltro.sql.
            /// </summary>
            public static readonly CommandInfo ObterSumarizadoPorFiltro = new CommandInfo( "ObterSumarizadoPorFiltro", "Inventario", "Inventario.ObterSumarizadoPorFiltro.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Inventario.ObterUltimoPorLojaDepartamento.sql.
            /// </summary>
            public static readonly CommandInfo ObterUltimoPorLojaDepartamento = new CommandInfo( "ObterUltimoPorLojaDepartamento", "Inventario", "Inventario.ObterUltimoPorLojaDepartamento.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Inventario.PossuiItemComCustoDeCadastro.sql.
            /// </summary>
            public static readonly CommandInfo PossuiItemComCustoDeCadastro = new CommandInfo( "PossuiItemComCustoDeCadastro", "Inventario", "Inventario.PossuiItemComCustoDeCadastro.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Inventario.PossuiItemInativoDeletado.sql.
            /// </summary>
            public static readonly CommandInfo PossuiItemInativoDeletado = new CommandInfo( "PossuiItemInativoDeletado", "Inventario", "Inventario.PossuiItemInativoDeletado.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Inventario.PossuiItemVinculadoEntrada.sql.
            /// </summary>
            public static readonly CommandInfo PossuiItemVinculadoEntrada = new CommandInfo( "PossuiItemVinculadoEntrada", "Inventario", "Inventario.PossuiItemVinculadoEntrada.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Inventario.PossuiSortimentoInvalido.sql.
            /// </summary>
            public static readonly CommandInfo PossuiSortimentoInvalido = new CommandInfo( "PossuiSortimentoInvalido", "Inventario", "Inventario.PossuiSortimentoInvalido.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe InventarioAgendamento.
        /// </summary>
        public static class InventarioAgendamento 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo InventarioAgendamento.ContarAgendamentos.sql.
            /// </summary>
            public static readonly CommandInfo ContarAgendamentos = new CommandInfo( "ContarAgendamentos", "InventarioAgendamento", "InventarioAgendamento.ContarAgendamentos.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo InventarioAgendamento.ObterAgendamentos.sql.
            /// </summary>
            public static readonly CommandInfo ObterAgendamentos = new CommandInfo( "ObterAgendamentos", "InventarioAgendamento", "InventarioAgendamento.ObterAgendamentos.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo InventarioAgendamento.ObterEstruturadosPorIds.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadosPorIds = new CommandInfo( "ObterEstruturadosPorIds", "InventarioAgendamento", "InventarioAgendamento.ObterEstruturadosPorIds.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo InventarioAgendamento.ObterNaoAgendados.sql.
            /// </summary>
            public static readonly CommandInfo ObterNaoAgendados = new CommandInfo( "ObterNaoAgendados", "InventarioAgendamento", "InventarioAgendamento.ObterNaoAgendados.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo InventarioAgendamento.ObterQuantidadeAgendamentos.sql.
            /// </summary>
            public static readonly CommandInfo ObterQuantidadeAgendamentos = new CommandInfo( "ObterQuantidadeAgendamentos", "InventarioAgendamento", "InventarioAgendamento.ObterQuantidadeAgendamentos.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe InventarioCritica.
        /// </summary>
        public static class InventarioCritica 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo InventarioCritica.ExcluirInventarioCritica.sql.
            /// </summary>
            public static readonly CommandInfo ExcluirInventarioCritica = new CommandInfo( "ExcluirInventarioCritica", "InventarioCritica", "InventarioCritica.ExcluirInventarioCritica.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo InventarioCritica.Pesquisar.sql.
            /// </summary>
            public static readonly CommandInfo Pesquisar = new CommandInfo( "Pesquisar", "InventarioCritica", "InventarioCritica.Pesquisar.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe InventarioItem.
        /// </summary>
        public static class InventarioItem 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo InventarioItem.ObterEstruturadoPorFiltro.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorFiltro = new CommandInfo( "ObterEstruturadoPorFiltro", "InventarioItem", "InventarioItem.ObterEstruturadoPorFiltro.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo InventarioItem.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "InventarioItem", "InventarioItem.ObterEstruturadoPorId.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe ItemDetalhe.
        /// </summary>
        public static class ItemDetalhe 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.AlterarDadosCustos.sql.
            /// </summary>
            public static readonly CommandInfo AlterarDadosCustos = new CommandInfo( "AlterarDadosCustos", "ItemDetalhe", "ItemDetalhe.AlterarDadosCustos.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.EstaVinculadoCompraCasada.sql.
            /// </summary>
            public static readonly CommandInfo EstaVinculadoCompraCasada = new CommandInfo( "EstaVinculadoCompraCasada", "ItemDetalhe", "ItemDetalhe.EstaVinculadoCompraCasada.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ItemDetalheEntradaPertenceItemDetalheSaida.sql.
            /// </summary>
            public static readonly CommandInfo ItemDetalheEntradaPertenceItemDetalheSaida = new CommandInfo( "ItemDetalheEntradaPertenceItemDetalheSaida", "ItemDetalhe", "ItemDetalhe.ItemDetalheEntradaPertenceItemDetalheSaida.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ItemDetalheSaidaPertenceCD.sql.
            /// </summary>
            public static readonly CommandInfo ItemDetalheSaidaPertenceCD = new CommandInfo( "ItemDetalheSaidaPertenceCD", "ItemDetalhe", "ItemDetalhe.ItemDetalheSaidaPertenceCD.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ItemPertenceFornecedor.sql.
            /// </summary>
            public static readonly CommandInfo ItemPertenceFornecedor = new CommandInfo( "ItemPertenceFornecedor", "ItemDetalhe", "ItemDetalhe.ItemPertenceFornecedor.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterEstruturadoExtraPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoExtraPorId = new CommandInfo( "ObterEstruturadoExtraPorId", "ItemDetalhe", "ItemDetalhe.ObterEstruturadoExtraPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "ItemDetalhe", "ItemDetalhe.ObterEstruturadoPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterFornecedorParametro.sql.
            /// </summary>
            public static readonly CommandInfo ObterFornecedorParametro = new CommandInfo( "ObterFornecedorParametro", "ItemDetalhe", "ItemDetalhe.ObterFornecedorParametro.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterInformacoesEstoquePorLoja_Count.sql.
            /// </summary>
            public static readonly CommandInfo ObterInformacoesEstoquePorLoja_Count = new CommandInfo( "ObterInformacoesEstoquePorLoja_Count", "ItemDetalhe", "ItemDetalhe.ObterInformacoesEstoquePorLoja_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterInformacoesEstoquePorLoja_Paging.sql.
            /// </summary>
            public static readonly CommandInfo ObterInformacoesEstoquePorLoja_Paging = new CommandInfo( "ObterInformacoesEstoquePorLoja_Paging", "ItemDetalhe", "ItemDetalhe.ObterInformacoesEstoquePorLoja_Paging.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterItemCustos_Count.sql.
            /// </summary>
            public static readonly CommandInfo ObterItemCustos_Count = new CommandInfo( "ObterItemCustos_Count", "ItemDetalhe", "ItemDetalhe.ObterItemCustos_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterItemCustos_Paging.sql.
            /// </summary>
            public static readonly CommandInfo ObterItemCustos_Paging = new CommandInfo( "ObterItemCustos_Paging", "ItemDetalhe", "ItemDetalhe.ObterItemCustos_Paging.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterItemEntradaPorItemSaida.sql.
            /// </summary>
            public static readonly CommandInfo ObterItemEntradaPorItemSaida = new CommandInfo( "ObterItemEntradaPorItemSaida", "ItemDetalhe", "ItemDetalhe.ObterItemEntradaPorItemSaida.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterItemSaidaPorFornecedorItemEntrada.sql.
            /// </summary>
            public static readonly CommandInfo ObterItemSaidaPorFornecedorItemEntrada = new CommandInfo( "ObterItemSaidaPorFornecedorItemEntrada", "ItemDetalhe", "ItemDetalhe.ObterItemSaidaPorFornecedorItemEntrada.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterItemSaidaPorFornecedorItemEntrada_Count.sql.
            /// </summary>
            public static readonly CommandInfo ObterItemSaidaPorFornecedorItemEntrada_Count = new CommandInfo( "ObterItemSaidaPorFornecedorItemEntrada_Count", "ItemDetalhe", "ItemDetalhe.ObterItemSaidaPorFornecedorItemEntrada_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterItemSaidaPorFornecedorItemEntrada_Paging.sql.
            /// </summary>
            public static readonly CommandInfo ObterItemSaidaPorFornecedorItemEntrada_Paging = new CommandInfo( "ObterItemSaidaPorFornecedorItemEntrada_Paging", "ItemDetalhe", "ItemDetalhe.ObterItemSaidaPorFornecedorItemEntrada_Paging.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterItensDetalheReturnSheet.sql.
            /// </summary>
            public static readonly CommandInfo ObterItensDetalheReturnSheet = new CommandInfo( "ObterItensDetalheReturnSheet", "ItemDetalhe", "ItemDetalhe.ObterItensDetalheReturnSheet.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterPorItemESistema.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorItemESistema = new CommandInfo( "ObterPorItemESistema", "ItemDetalhe", "ItemDetalhe.ObterPorItemESistema.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterPorOldNumberESistemaEDepartamento.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorOldNumberESistemaEDepartamento = new CommandInfo( "ObterPorOldNumberESistemaEDepartamento", "ItemDetalhe", "ItemDetalhe.ObterPorOldNumberESistemaEDepartamento.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterPorPluESistema.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorPluESistema = new CommandInfo( "ObterPorPluESistema", "ItemDetalhe", "ItemDetalhe.ObterPorPluESistema.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterTraitsPorItem.sql.
            /// </summary>
            public static readonly CommandInfo ObterTraitsPorItem = new CommandInfo( "ObterTraitsPorItem", "ItemDetalhe", "ItemDetalhe.ObterTraitsPorItem.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.ObterValorTipoReabastecimento.sql.
            /// </summary>
            public static readonly CommandInfo ObterValorTipoReabastecimento = new CommandInfo( "ObterValorTipoReabastecimento", "ItemDetalhe", "ItemDetalhe.ObterValorTipoReabastecimento.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.PesquisarAbertoPorBandeira_Count.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarAbertoPorBandeira_Count = new CommandInfo( "PesquisarAbertoPorBandeira_Count", "ItemDetalhe", "ItemDetalhe.PesquisarAbertoPorBandeira_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.PesquisarAbertoPorBandeira_Paging.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarAbertoPorBandeira_Paging = new CommandInfo( "PesquisarAbertoPorBandeira_Paging", "ItemDetalhe", "ItemDetalhe.PesquisarAbertoPorBandeira_Paging.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.PesquisarItemCD.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarItemCD = new CommandInfo( "PesquisarItemCD", "ItemDetalhe", "ItemDetalhe.PesquisarItemCD.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.PesquisarItensEntradaPorSaidaCD.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarItensEntradaPorSaidaCD = new CommandInfo( "PesquisarItensEntradaPorSaidaCD", "ItemDetalhe", "ItemDetalhe.PesquisarItensEntradaPorSaidaCD.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.PesquisarItensEntradaPorSaidaCD_Count.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarItensEntradaPorSaidaCD_Count = new CommandInfo( "PesquisarItensEntradaPorSaidaCD_Count", "ItemDetalhe", "ItemDetalhe.PesquisarItensEntradaPorSaidaCD_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.PesquisarPorFiltros.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltros = new CommandInfo( "PesquisarPorFiltros", "ItemDetalhe", "ItemDetalhe.PesquisarPorFiltros.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.PesquisarPorFiltrosComTipoReabastecimento.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltrosComTipoReabastecimento = new CommandInfo( "PesquisarPorFiltrosComTipoReabastecimento", "ItemDetalhe", "ItemDetalhe.PesquisarPorFiltrosComTipoReabastecimento.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.PesquisarPorFiltros_Count.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltros_Count = new CommandInfo( "PesquisarPorFiltros_Count", "ItemDetalhe", "ItemDetalhe.PesquisarPorFiltros_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ItemDetalhe.PesquisarPorFiltros_Paging.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltros_Paging = new CommandInfo( "PesquisarPorFiltros_Paging", "ItemDetalhe", "ItemDetalhe.PesquisarPorFiltros_Paging.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Loja.
        /// </summary>
        public static class Loja 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Loja.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "Loja", "Loja.ObterEstruturadoPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Loja.ObterPorBandeira.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorBandeira = new CommandInfo( "ObterPorBandeira", "Loja", "Loja.ObterPorBandeira.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Loja.Pesquisar.sql.
            /// </summary>
            public static readonly CommandInfo Pesquisar = new CommandInfo( "Pesquisar", "Loja", "Loja.Pesquisar.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Loja.PesquisarPorItemDestinoOrigem.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorItemDestinoOrigem = new CommandInfo( "PesquisarPorItemDestinoOrigem", "Loja", "Loja.PesquisarPorItemDestinoOrigem.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Loja.Pesquisar_Count.sql.
            /// </summary>
            public static readonly CommandInfo Pesquisar_Count = new CommandInfo( "Pesquisar_Count", "Loja", "Loja.Pesquisar_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Loja.Pesquisar_Paging.sql.
            /// </summary>
            public static readonly CommandInfo Pesquisar_Paging = new CommandInfo( "Pesquisar_Paging", "Loja", "Loja.Pesquisar_Paging.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe LojaCdParametro.
        /// </summary>
        public static class LojaCdParametro 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo LojaCdParametro.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "LojaCdParametro", "LojaCdParametro.ObterEstruturadoPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo LojaCdParametro.PesquisarPorFiltros_Count.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltros_Count = new CommandInfo( "PesquisarPorFiltros_Count", "LojaCdParametro", "LojaCdParametro.PesquisarPorFiltros_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo LojaCdParametro.PesquisarPorFiltros_Paging.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltros_Paging = new CommandInfo( "PesquisarPorFiltros_Paging", "LojaCdParametro", "LojaCdParametro.PesquisarPorFiltros_Paging.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Movimentacao.
        /// </summary>
        public static class Movimentacao 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Movimentacao.ObterDatasDeQuebra.sql.
            /// </summary>
            public static readonly CommandInfo ObterDatasDeQuebra = new CommandInfo( "ObterDatasDeQuebra", "Movimentacao", "Movimentacao.ObterDatasDeQuebra.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Movimentacao.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "Movimentacao", "Movimentacao.ObterEstruturadoPorId.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Multisourcing.
        /// </summary>
        public static class Multisourcing 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Multisourcing.ObtemItemDetalheSaidaEntradaMultisourcing.sql.
            /// </summary>
            public static readonly CommandInfo ObtemItemDetalheSaidaEntradaMultisourcing = new CommandInfo( "ObtemItemDetalheSaidaEntradaMultisourcing", "Multisourcing", "Multisourcing.ObtemItemDetalheSaidaEntradaMultisourcing.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Multisourcing.ObterComDetalhes.sql.
            /// </summary>
            public static readonly CommandInfo ObterComDetalhes = new CommandInfo( "ObterComDetalhes", "Multisourcing", "Multisourcing.ObterComDetalhes.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Multisourcing.ObterPorCdItemSaidaEcdCD.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorCdItemSaidaEcdCD = new CommandInfo( "ObterPorCdItemSaidaEcdCD", "Multisourcing", "Multisourcing.ObterPorCdItemSaidaEcdCD.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Multisourcing.VerificarRipVinculado.sql.
            /// </summary>
            public static readonly CommandInfo VerificarRipVinculado = new CommandInfo( "VerificarRipVinculado", "Multisourcing", "Multisourcing.VerificarRipVinculado.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe NotaFiscal.
        /// </summary>
        public static class NotaFiscal 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo NotaFiscal.ExisteNotasPendentesPorItem.sql.
            /// </summary>
            public static readonly CommandInfo ExisteNotasPendentesPorItem = new CommandInfo( "ExisteNotasPendentesPorItem", "NotaFiscal", "NotaFiscal.ExisteNotasPendentesPorItem.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo NotaFiscal.ObterCustosPorItem.sql.
            /// </summary>
            public static readonly CommandInfo ObterCustosPorItem = new CommandInfo( "ObterCustosPorItem", "NotaFiscal", "NotaFiscal.ObterCustosPorItem.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo NotaFiscal.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "NotaFiscal", "NotaFiscal.ObterEstruturadoPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo NotaFiscal.ObterItemNaUltimaNotaRecebidaDaLoja.sql.
            /// </summary>
            public static readonly CommandInfo ObterItemNaUltimaNotaRecebidaDaLoja = new CommandInfo( "ObterItemNaUltimaNotaRecebidaDaLoja", "NotaFiscal", "NotaFiscal.ObterItemNaUltimaNotaRecebidaDaLoja.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo NotaFiscal.ObterItensDaNotaFiscal.sql.
            /// </summary>
            public static readonly CommandInfo ObterItensDaNotaFiscal = new CommandInfo( "ObterItensDaNotaFiscal", "NotaFiscal", "NotaFiscal.ObterItensDaNotaFiscal.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo NotaFiscal.PesquisarCustosPorFiltros.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarCustosPorFiltros = new CommandInfo( "PesquisarCustosPorFiltros", "NotaFiscal", "NotaFiscal.PesquisarCustosPorFiltros.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo NotaFiscal.PesquisarPorFiltros.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltros = new CommandInfo( "PesquisarPorFiltros", "NotaFiscal", "NotaFiscal.PesquisarPorFiltros.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo NotaFiscal.PesquisarUltimasEntradasPorFiltros.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarUltimasEntradasPorFiltros = new CommandInfo( "PesquisarUltimasEntradasPorFiltros", "NotaFiscal", "NotaFiscal.PesquisarUltimasEntradasPorFiltros.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Parametro.
        /// </summary>
        public static class Parametro 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Parametro.ObterEstruturado.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturado = new CommandInfo( "ObterEstruturado", "Parametro", "Parametro.ObterEstruturado.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Permissao.
        /// </summary>
        public static class Permissao 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Permissao.ObterPermissoesDoUsuario.sql.
            /// </summary>
            public static readonly CommandInfo ObterPermissoesDoUsuario = new CommandInfo( "ObterPermissoesDoUsuario", "Permissao", "Permissao.ObterPermissoesDoUsuario.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Permissao.ObterPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorId = new CommandInfo( "ObterPorId", "Permissao", "Permissao.ObterPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Permissao.Pesquisar.sql.
            /// </summary>
            public static readonly CommandInfo Pesquisar = new CommandInfo( "Pesquisar", "Permissao", "Permissao.Pesquisar.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Permissao.PesquisarComFilhos_Count.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarComFilhos_Count = new CommandInfo( "PesquisarComFilhos_Count", "Permissao", "Permissao.PesquisarComFilhos_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Permissao.PesquisarComFilhos_Paging.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarComFilhos_Paging = new CommandInfo( "PesquisarComFilhos_Paging", "Permissao", "Permissao.PesquisarComFilhos_Paging.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Permissao.PossuiPermissaoLoja.sql.
            /// </summary>
            public static readonly CommandInfo PossuiPermissaoLoja = new CommandInfo( "PossuiPermissaoLoja", "Permissao", "Permissao.PossuiPermissaoLoja.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe PermissaoBandeira.
        /// </summary>
        public static class PermissaoBandeira 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo PermissaoBandeira.UsuarioPossuiPermissaoBandeira.sql.
            /// </summary>
            public static readonly CommandInfo UsuarioPossuiPermissaoBandeira = new CommandInfo( "UsuarioPossuiPermissaoBandeira", "PermissaoBandeira", "PermissaoBandeira.UsuarioPossuiPermissaoBandeira.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe PermissaoLoja.
        /// </summary>
        public static class PermissaoLoja 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo PermissaoLoja.UsuarioPossuiPermissaoLoja.sql.
            /// </summary>
            public static readonly CommandInfo UsuarioPossuiPermissaoLoja = new CommandInfo( "UsuarioPossuiPermissaoLoja", "PermissaoLoja", "PermissaoLoja.UsuarioPossuiPermissaoLoja.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Processo.
        /// </summary>
        public static class Processo 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Processo.PesquisarCargas_Count.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarCargas_Count = new CommandInfo( "PesquisarCargas_Count", "Processo", "Processo.PesquisarCargas_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Processo.PesquisarCargas_Paging.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarCargas_Paging = new CommandInfo( "PesquisarCargas_Paging", "Processo", "Processo.PesquisarCargas_Paging.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Processo.PesquisarProcessosExecucao.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarProcessosExecucao = new CommandInfo( "PesquisarProcessosExecucao", "Processo", "Processo.PesquisarProcessosExecucao.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe ProcessOrder.
        /// </summary>
        public static class ProcessOrder 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ProcessOrder.FindAllByUser_Count.sql.
            /// </summary>
            public static readonly CommandInfo FindAllByUser_Count = new CommandInfo( "FindAllByUser_Count", "ProcessOrder", "ProcessOrder.FindAllByUser_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ProcessOrder.FindAllByUser_Paging.sql.
            /// </summary>
            public static readonly CommandInfo FindAllByUser_Paging = new CommandInfo( "FindAllByUser_Paging", "ProcessOrder", "ProcessOrder.FindAllByUser_Paging.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ProcessOrder.FindAllReadyToBeRemoved.sql.
            /// </summary>
            public static readonly CommandInfo FindAllReadyToBeRemoved = new CommandInfo( "FindAllReadyToBeRemoved", "ProcessOrder", "ProcessOrder.FindAllReadyToBeRemoved.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ProcessOrder.GetNextTicketToRun.sql.
            /// </summary>
            public static readonly CommandInfo GetNextTicketToRun = new CommandInfo( "GetNextTicketToRun", "ProcessOrder", "ProcessOrder.GetNextTicketToRun.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ProcessOrder.GetProcessOrderDetail.sql.
            /// </summary>
            public static readonly CommandInfo GetProcessOrderDetail = new CommandInfo( "GetProcessOrderDetail", "ProcessOrder", "ProcessOrder.GetProcessOrderDetail.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe ProcessOrderArgument.
        /// </summary>
        public static class ProcessOrderArgument 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ProcessOrderArgument.HasFileVaultTicket.sql.
            /// </summary>
            public static readonly CommandInfo HasFileVaultTicket = new CommandInfo( "HasFileVaultTicket", "ProcessOrderArgument", "ProcessOrderArgument.HasFileVaultTicket.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe RelacaoItemLojaCD.
        /// </summary>
        public static class RelacaoItemLojaCD 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.Cadastro_Count.sql.
            /// </summary>
            public static readonly CommandInfo Cadastro_Count = new CommandInfo( "Cadastro_Count", "RelacaoItemLojaCD", "RelacaoItemLojaCD.Cadastro_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ExportacaoCadastroReabastecimento.sql.
            /// </summary>
            public static readonly CommandInfo ExportacaoCadastroReabastecimento = new CommandInfo( "ExportacaoCadastroReabastecimento", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ExportacaoCadastroReabastecimento.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ItemXrefPrime.sql.
            /// </summary>
            public static readonly CommandInfo ItemXrefPrime = new CommandInfo( "ItemXrefPrime", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ItemXrefPrime.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.LojaCDPossuiCadastroItemControleEstoque.sql.
            /// </summary>
            public static readonly CommandInfo LojaCDPossuiCadastroItemControleEstoque = new CommandInfo( "LojaCDPossuiCadastroItemControleEstoque", "RelacaoItemLojaCD", "RelacaoItemLojaCD.LojaCDPossuiCadastroItemControleEstoque.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ObterDadosImportacao.sql.
            /// </summary>
            public static readonly CommandInfo ObterDadosImportacao = new CommandInfo( "ObterDadosImportacao", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ObterDadosImportacao.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ObterItemEntradaDisponivel.sql.
            /// </summary>
            public static readonly CommandInfo ObterItemEntradaDisponivel = new CommandInfo( "ObterItemEntradaDisponivel", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ObterItemEntradaDisponivel.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ObterItemSaidaAtendeRequisitos.sql.
            /// </summary>
            public static readonly CommandInfo ObterItemSaidaAtendeRequisitos = new CommandInfo( "ObterItemSaidaAtendeRequisitos", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ObterItemSaidaAtendeRequisitos.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ObterPorFiltro_Count.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorFiltro_Count = new CommandInfo( "ObterPorFiltro_Count", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ObterPorFiltro_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ObterPorFiltro_Paging.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorFiltro_Paging = new CommandInfo( "ObterPorFiltro_Paging", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ObterPorFiltro_Paging.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ObterPorVinculo.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorVinculo = new CommandInfo( "ObterPorVinculo", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ObterPorVinculo.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ObterProcessamentosImportacao_Count.sql.
            /// </summary>
            public static readonly CommandInfo ObterProcessamentosImportacao_Count = new CommandInfo( "ObterProcessamentosImportacao_Count", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ObterProcessamentosImportacao_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ObterProcessamentosImportacao_Paging.sql.
            /// </summary>
            public static readonly CommandInfo ObterProcessamentosImportacao_Paging = new CommandInfo( "ObterProcessamentosImportacao_Paging", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ObterProcessamentosImportacao_Paging.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ObterQtdCDAtivos.sql.
            /// </summary>
            public static readonly CommandInfo ObterQtdCDAtivos = new CommandInfo( "ObterQtdCDAtivos", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ObterQtdCDAtivos.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ObterQtdLojasAtivas.sql.
            /// </summary>
            public static readonly CommandInfo ObterQtdLojasAtivas = new CommandInfo( "ObterQtdLojasAtivas", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ObterQtdLojasAtivas.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.ObterTipoReabastecimentoItemVinculadoXrefPrime.sql.
            /// </summary>
            public static readonly CommandInfo ObterTipoReabastecimentoItemVinculadoXrefPrime = new CommandInfo( "ObterTipoReabastecimentoItemVinculadoXrefPrime", "RelacaoItemLojaCD", "RelacaoItemLojaCD.ObterTipoReabastecimentoItemVinculadoXrefPrime.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.PossuiRelacionamento.sql.
            /// </summary>
            public static readonly CommandInfo PossuiRelacionamento = new CommandInfo( "PossuiRelacionamento", "RelacaoItemLojaCD", "RelacaoItemLojaCD.PossuiRelacionamento.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.RelacionamentoSGP_Count.sql.
            /// </summary>
            public static readonly CommandInfo RelacionamentoSGP_Count = new CommandInfo( "RelacionamentoSGP_Count", "RelacaoItemLojaCD", "RelacaoItemLojaCD.RelacionamentoSGP_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.VerificaLojaAtendidaCD.sql.
            /// </summary>
            public static readonly CommandInfo VerificaLojaAtendidaCD = new CommandInfo( "VerificaLojaAtendidaCD", "RelacaoItemLojaCD", "RelacaoItemLojaCD.VerificaLojaAtendidaCD.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacaoItemLojaCD.VerificarItemXrefPossuiSecundarios.sql.
            /// </summary>
            public static readonly CommandInfo VerificarItemXrefPossuiSecundarios = new CommandInfo( "VerificarItemXrefPossuiSecundarios", "RelacaoItemLojaCD", "RelacaoItemLojaCD.VerificarItemXrefPossuiSecundarios.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe RelacionamentoItemPrincipal.
        /// </summary>
        public static class RelacionamentoItemPrincipal 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoItemPrincipal.ContarItemDetalheComoSaidaEmOutrosRelacionamentos.sql.
            /// </summary>
            public static readonly CommandInfo ContarItemDetalheComoSaidaEmOutrosRelacionamentos = new CommandInfo( "ContarItemDetalheComoSaidaEmOutrosRelacionamentos", "RelacionamentoItemPrincipal", "RelacionamentoItemPrincipal.ContarItemDetalheComoSaidaEmOutrosRelacionamentos.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoItemPrincipal.ContarItemDetalheEmOutrosRelacionamentos.sql.
            /// </summary>
            public static readonly CommandInfo ContarItemDetalheEmOutrosRelacionamentos = new CommandInfo( "ContarItemDetalheEmOutrosRelacionamentos", "RelacionamentoItemPrincipal", "RelacionamentoItemPrincipal.ContarItemDetalheEmOutrosRelacionamentos.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoItemPrincipal.ObterPercentualRendimentoTransformado.sql.
            /// </summary>
            public static readonly CommandInfo ObterPercentualRendimentoTransformado = new CommandInfo( "ObterPercentualRendimentoTransformado", "RelacionamentoItemPrincipal", "RelacionamentoItemPrincipal.ObterPercentualRendimentoTransformado.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoItemPrincipal.ObterPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorId = new CommandInfo( "ObterPorId", "RelacionamentoItemPrincipal", "RelacionamentoItemPrincipal.ObterPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoItemPrincipal.ObterPrincipaisPorItem.sql.
            /// </summary>
            public static readonly CommandInfo ObterPrincipaisPorItem = new CommandInfo( "ObterPrincipaisPorItem", "RelacionamentoItemPrincipal", "RelacionamentoItemPrincipal.ObterPrincipaisPorItem.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoItemPrincipal.PesquisarPorTipoRelacionamento.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorTipoRelacionamento = new CommandInfo( "PesquisarPorTipoRelacionamento", "RelacionamentoItemPrincipal", "RelacionamentoItemPrincipal.PesquisarPorTipoRelacionamento.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe RelacionamentoItemSecundario.
        /// </summary>
        public static class RelacionamentoItemSecundario 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoItemSecundario.ObterPercentualRendimentoDerivado.sql.
            /// </summary>
            public static readonly CommandInfo ObterPercentualRendimentoDerivado = new CommandInfo( "ObterPercentualRendimentoDerivado", "RelacionamentoItemSecundario", "RelacionamentoItemSecundario.ObterPercentualRendimentoDerivado.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoItemSecundario.ObterSecundariosPorItem.sql.
            /// </summary>
            public static readonly CommandInfo ObterSecundariosPorItem = new CommandInfo( "ObterSecundariosPorItem", "RelacionamentoItemSecundario", "RelacionamentoItemSecundario.ObterSecundariosPorItem.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe RelacionamentoTransferencia.
        /// </summary>
        public static class RelacionamentoTransferencia 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoTransferencia.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "RelacionamentoTransferencia", "RelacionamentoTransferencia.ObterEstruturadoPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoTransferencia.ObterQuantidadePorItemDestino.sql.
            /// </summary>
            public static readonly CommandInfo ObterQuantidadePorItemDestino = new CommandInfo( "ObterQuantidadePorItemDestino", "RelacionamentoTransferencia", "RelacionamentoTransferencia.ObterQuantidadePorItemDestino.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoTransferencia.PesquisarItensRelacionados.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarItensRelacionados = new CommandInfo( "PesquisarItensRelacionados", "RelacionamentoTransferencia", "RelacionamentoTransferencia.PesquisarItensRelacionados.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoTransferencia.PesquisarItensRelacionadosPorCdItemDestino.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarItensRelacionadosPorCdItemDestino = new CommandInfo( "PesquisarItensRelacionadosPorCdItemDestino", "RelacionamentoTransferencia", "RelacionamentoTransferencia.PesquisarItensRelacionadosPorCdItemDestino.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoTransferencia.PesquisarPorFiltro.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltro = new CommandInfo( "PesquisarPorFiltro", "RelacionamentoTransferencia", "RelacionamentoTransferencia.PesquisarPorFiltro.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RelacionamentoTransferencia.PesquisarPorItemDestinoOrigemLojaStatus.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorItemDestinoOrigemLojaStatus = new CommandInfo( "PesquisarPorItemDestinoOrigemLojaStatus", "RelacionamentoTransferencia", "RelacionamentoTransferencia.PesquisarPorItemDestinoOrigemLojaStatus.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe ReturnSheet.
        /// </summary>
        public static class ReturnSheet 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ReturnSheet.Pesquisar.sql.
            /// </summary>
            public static readonly CommandInfo Pesquisar = new CommandInfo( "Pesquisar", "ReturnSheet", "ReturnSheet.Pesquisar.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ReturnSheet.PossuiAutorizacao.sql.
            /// </summary>
            public static readonly CommandInfo PossuiAutorizacao = new CommandInfo( "PossuiAutorizacao", "ReturnSheet", "ReturnSheet.PossuiAutorizacao.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ReturnSheet.PossuiExportacao.sql.
            /// </summary>
            public static readonly CommandInfo PossuiExportacao = new CommandInfo( "PossuiExportacao", "ReturnSheet", "ReturnSheet.PossuiExportacao.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe ReturnSheetItemLoja.
        /// </summary>
        public static class ReturnSheetItemLoja 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ReturnSheetItemLoja.ObterEstadosLojasValidasItem.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstadosLojasValidasItem = new CommandInfo( "ObterEstadosLojasValidasItem", "ReturnSheetItemLoja", "ReturnSheetItemLoja.ObterEstadosLojasValidasItem.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ReturnSheetItemLoja.ObterLojasPorReturnSheetEItemDetalheSaida.sql.
            /// </summary>
            public static readonly CommandInfo ObterLojasPorReturnSheetEItemDetalheSaida = new CommandInfo( "ObterLojasPorReturnSheetEItemDetalheSaida", "ReturnSheetItemLoja", "ReturnSheetItemLoja.ObterLojasPorReturnSheetEItemDetalheSaida.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ReturnSheetItemLoja.ObterLojasValidasItem.sql.
            /// </summary>
            public static readonly CommandInfo ObterLojasValidasItem = new CommandInfo( "ObterLojasValidasItem", "ReturnSheetItemLoja", "ReturnSheetItemLoja.ObterLojasValidasItem.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe ReturnSheetItemPrincipal.
        /// </summary>
        public static class ReturnSheetItemPrincipal 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ReturnSheetItemPrincipal.ObterPorReturnSheetEItemDetalheSaida.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorReturnSheetEItemDetalheSaida = new CommandInfo( "ObterPorReturnSheetEItemDetalheSaida", "ReturnSheetItemPrincipal", "ReturnSheetItemPrincipal.ObterPorReturnSheetEItemDetalheSaida.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo ReturnSheetItemPrincipal.PesquisarPorIdReturnSheet.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorIdReturnSheet = new CommandInfo( "PesquisarPorIdReturnSheet", "ReturnSheetItemPrincipal", "ReturnSheetItemPrincipal.PesquisarPorIdReturnSheet.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe RevisaoCusto.
        /// </summary>
        public static class RevisaoCusto 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RevisaoCusto.ObterEstruturadoPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturadoPorId = new CommandInfo( "ObterEstruturadoPorId", "RevisaoCusto", "RevisaoCusto.ObterEstruturadoPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RevisaoCusto.PesquisarPorFiltros.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltros = new CommandInfo( "PesquisarPorFiltros", "RevisaoCusto", "RevisaoCusto.PesquisarPorFiltros.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Roteiro.
        /// </summary>
        public static class Roteiro 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Roteiro.ObterItemLojaRoteiroDetalhe.sql.
            /// </summary>
            public static readonly CommandInfo ObterItemLojaRoteiroDetalhe = new CommandInfo( "ObterItemLojaRoteiroDetalhe", "Roteiro", "Roteiro.ObterItemLojaRoteiroDetalhe.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Roteiro.ObterPorId.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorId = new CommandInfo( "ObterPorId", "Roteiro", "Roteiro.ObterPorId.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Roteiro.ObterPorIdComLojas.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorIdComLojas = new CommandInfo( "ObterPorIdComLojas", "Roteiro", "Roteiro.ObterPorIdComLojas.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Roteiro.ObterRoteirosPorFornecedor.sql.
            /// </summary>
            public static readonly CommandInfo ObterRoteirosPorFornecedor = new CommandInfo( "ObterRoteirosPorFornecedor", "Roteiro", "Roteiro.ObterRoteirosPorFornecedor.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe RoteiroLoja.
        /// </summary>
        public static class RoteiroLoja 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RoteiroLoja.ObterLojasValidas.sql.
            /// </summary>
            public static readonly CommandInfo ObterLojasValidas = new CommandInfo( "ObterLojasValidas", "RoteiroLoja", "RoteiroLoja.ObterLojasValidas.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe RoteiroPedido.
        /// </summary>
        public static class RoteiroPedido 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RoteiroPedido.ObterDadosAutorizacao.sql.
            /// </summary>
            public static readonly CommandInfo ObterDadosAutorizacao = new CommandInfo( "ObterDadosAutorizacao", "RoteiroPedido", "RoteiroPedido.ObterDadosAutorizacao.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RoteiroPedido.ObterPedidosRoteirizados.sql.
            /// </summary>
            public static readonly CommandInfo ObterPedidosRoteirizados = new CommandInfo( "ObterPedidosRoteirizados", "RoteiroPedido", "RoteiroPedido.ObterPedidosRoteirizados.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RoteiroPedido.ObterRoteirosPedidosParaAutorizar.sql.
            /// </summary>
            public static readonly CommandInfo ObterRoteirosPedidosParaAutorizar = new CommandInfo( "ObterRoteirosPedidosParaAutorizar", "RoteiroPedido", "RoteiroPedido.ObterRoteirosPedidosParaAutorizar.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RoteiroPedido.ObterRoteirosPedidosPorRoteiroEdtPedido.sql.
            /// </summary>
            public static readonly CommandInfo ObterRoteirosPedidosPorRoteiroEdtPedido = new CommandInfo( "ObterRoteirosPedidosPorRoteiroEdtPedido", "RoteiroPedido", "RoteiroPedido.ObterRoteirosPedidosPorRoteiroEdtPedido.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RoteiroPedido.ObterSugestaoPedidoPorRoteiro.sql.
            /// </summary>
            public static readonly CommandInfo ObterSugestaoPedidoPorRoteiro = new CommandInfo( "ObterSugestaoPedidoPorRoteiro", "RoteiroPedido", "RoteiroPedido.ObterSugestaoPedidoPorRoteiro.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RoteiroPedido.ObterSugestaoPedidoPorRoteiroItem.sql.
            /// </summary>
            public static readonly CommandInfo ObterSugestaoPedidoPorRoteiroItem = new CommandInfo( "ObterSugestaoPedidoPorRoteiroItem", "RoteiroPedido", "RoteiroPedido.ObterSugestaoPedidoPorRoteiroItem.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo RoteiroPedido.QtdPedidosNaoAutorizadosParaDataCorrente.sql.
            /// </summary>
            public static readonly CommandInfo QtdPedidosNaoAutorizadosParaDataCorrente = new CommandInfo( "QtdPedidosNaoAutorizadosParaDataCorrente", "RoteiroPedido", "RoteiroPedido.QtdPedidosNaoAutorizadosParaDataCorrente.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Sistema.
        /// </summary>
        public static class Sistema 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Sistema.ObterPorUsuario.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorUsuario = new CommandInfo( "ObterPorUsuario", "Sistema", "Sistema.ObterPorUsuario.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe StatusItemHost.
        /// </summary>
        public static class StatusItemHost 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo StatusItemHost.ObterPorCultura.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorCultura = new CommandInfo( "ObterPorCultura", "StatusItemHost", "StatusItemHost.ObterPorCultura.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Subcategoria.
        /// </summary>
        public static class Subcategoria 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Subcategoria.ObterPorSubcategoriaESistema.sql.
            /// </summary>
            public static readonly CommandInfo ObterPorSubcategoriaESistema = new CommandInfo( "ObterPorSubcategoriaESistema", "Subcategoria", "Subcategoria.ObterPorSubcategoriaESistema.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Subcategoria.PesquisarPorSubcategoriaCategoriaDepartamentoESistema.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorSubcategoriaCategoriaDepartamentoESistema = new CommandInfo( "PesquisarPorSubcategoriaCategoriaDepartamentoESistema", "Subcategoria", "Subcategoria.PesquisarPorSubcategoriaCategoriaDepartamentoESistema.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe SugestaoPedido.
        /// </summary>
        public static class SugestaoPedido 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoPedido.ContarPorDataPedidoLojaEDepartamento.sql.
            /// </summary>
            public static readonly CommandInfo ContarPorDataPedidoLojaEDepartamento = new CommandInfo( "ContarPorDataPedidoLojaEDepartamento", "SugestaoPedido", "SugestaoPedido.ContarPorDataPedidoLojaEDepartamento.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoPedido.ObterDisponibilidade.sql.
            /// </summary>
            public static readonly CommandInfo ObterDisponibilidade = new CommandInfo( "ObterDisponibilidade", "SugestaoPedido", "SugestaoPedido.ObterDisponibilidade.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoPedido.ObterEstruturado.sql.
            /// </summary>
            public static readonly CommandInfo ObterEstruturado = new CommandInfo( "ObterEstruturado", "SugestaoPedido", "SugestaoPedido.ObterEstruturado.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoPedido.PesquisarPorFiltros_Count.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltros_Count = new CommandInfo( "PesquisarPorFiltros_Count", "SugestaoPedido", "SugestaoPedido.PesquisarPorFiltros_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoPedido.PesquisarPorFiltros_Paging.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFiltros_Paging = new CommandInfo( "PesquisarPorFiltros_Paging", "SugestaoPedido", "SugestaoPedido.PesquisarPorFiltros_Paging.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoPedido.PesquisarPorFornecedorParametroELoja.sql.
            /// </summary>
            public static readonly CommandInfo PesquisarPorFornecedorParametroELoja = new CommandInfo( "PesquisarPorFornecedorParametroELoja", "SugestaoPedido", "SugestaoPedido.PesquisarPorFornecedorParametroELoja.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoPedido.QtdPedidosGradeAberta.sql.
            /// </summary>
            public static readonly CommandInfo QtdPedidosGradeAberta = new CommandInfo( "QtdPedidosGradeAberta", "SugestaoPedido", "SugestaoPedido.QtdPedidosGradeAberta.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe SugestaoPedidoCD.
        /// </summary>
        public static class SugestaoPedidoCD 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoPedidoCD.ExisteSugestoesFinalizadasMesmoItemDetalheSaida.sql.
            /// </summary>
            public static readonly CommandInfo ExisteSugestoesFinalizadasMesmoItemDetalheSaida = new CommandInfo( "ExisteSugestoesFinalizadasMesmoItemDetalheSaida", "SugestaoPedidoCD", "SugestaoPedidoCD.ExisteSugestoesFinalizadasMesmoItemDetalheSaida.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoPedidoCD.ObterSugestoesPorFiltro.sql.
            /// </summary>
            public static readonly CommandInfo ObterSugestoesPorFiltro = new CommandInfo( "ObterSugestoesPorFiltro", "SugestaoPedidoCD", "SugestaoPedidoCD.ObterSugestoesPorFiltro.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoPedidoCD.Pesquisar.sql.
            /// </summary>
            public static readonly CommandInfo Pesquisar = new CommandInfo( "Pesquisar", "SugestaoPedidoCD", "SugestaoPedidoCD.Pesquisar.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoPedidoCD.QtdPedidosGradeAberta.sql.
            /// </summary>
            public static readonly CommandInfo QtdPedidosGradeAberta = new CommandInfo( "QtdPedidosGradeAberta", "SugestaoPedidoCD", "SugestaoPedidoCD.QtdPedidosGradeAberta.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe SugestaoReturnSheet.
        /// </summary>
        public static class SugestaoReturnSheet 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoReturnSheet.ConsultaLoja.sql.
            /// </summary>
            public static readonly CommandInfo ConsultaLoja = new CommandInfo( "ConsultaLoja", "SugestaoReturnSheet", "SugestaoReturnSheet.ConsultaLoja.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoReturnSheet.ConsultaReturnSheetRA.sql.
            /// </summary>
            public static readonly CommandInfo ConsultaReturnSheetRA = new CommandInfo( "ConsultaReturnSheetRA", "SugestaoReturnSheet", "SugestaoReturnSheet.ConsultaReturnSheetRA.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo SugestaoReturnSheet.PossuiReturnsVigentesQuantidadesVazias.sql.
            /// </summary>
            public static readonly CommandInfo PossuiReturnsVigentesQuantidadesVazias = new CommandInfo( "PossuiReturnsVigentesQuantidadesVazias", "SugestaoReturnSheet", "SugestaoReturnSheet.PossuiReturnsVigentesQuantidadesVazias.sql");
            
}
        /// <summary>
        /// Comandos SQL relacionados a classe Trait.
        /// </summary>
        public static class Trait 
        {  
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Trait.PesquisaPorItemSistemaELoja_Count.sql.
            /// </summary>
            public static readonly CommandInfo PesquisaPorItemSistemaELoja_Count = new CommandInfo( "PesquisaPorItemSistemaELoja_Count", "Trait", "Trait.PesquisaPorItemSistemaELoja_Count.sql");
            
/// <summary>
            /// O nome do comando SQL existente no arquivo Trait.PossuiTrait.sql.
            /// </summary>
            public static readonly CommandInfo PossuiTrait = new CommandInfo( "PossuiTrait", "Trait", "Trait.PossuiTrait.sql");
            
}
        }
    }
